name: lab_7

on:
  push:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: make
      run: |
        cd lab7
        make test
        make runtest
        make checkcov
